name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # daily
  workflow_dispatch:      # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    # Added permissions to allow the bot to write the image to your repo
    permissions:
      contents: write
      
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Your Personal Access Token (PAT)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Target: your organisation
          user: MaquestiauxLabs
          base: header, repositories

          # Output
          filename: metrics.svg
          committer_token: ${{ secrets.METRICS_TOKEN }}
          
          # Plugins
          plugin_traffic: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 12
          plugin_lines: yes
          plugin_repositories: yes
          plugin_repositories_affiliations: owner
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_issues: yes
          plugin_issues_labels: "*"
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_stars: yes
          plugin_stars_limit: 5
